from typing import Dict

new_names: Dict[str, str] = {
    "Indique su institución": "institucion",
    "Indique la cantidad de Bibliotecas en su institución": "nro_bibliotecas",
    "¿En su biblioteca existen software que dispongan de elementos asociados a la Inteligencia Artificial?. Por ejemplo: servicios de descubrimiento, chats.": "servicios_IA",
    "¿Se tienen planes a futuro para la implementación de IA en su biblioteca?": "planes_a_futuro",
    "¿Estima posible la implementación de la IA en las bibliotecas universitarias actualmente? ": "posible_Implementacion",
    "¿Qué aspectos considera que son relevantes en la implementación de IA en su biblioteca?. Puede seleccionar más de una.": "aspectos_relevantes",
    "Tomando en consideración aspectos como la atención al usuario, los servicios de la biblioteca, mejora de procesos internos de las bibliotecas, los trabajadores de las bibliotecas, entre otros. ¿Qué impacto cree que generaría la implementación de IA dentro de las  bibliotecas?. Puede seleccionar más de una.": "impacto_IA",
    "¿Qué nuevas tecnologías basadas en IA ha implementado o considera implementar en su biblioteca?. Puede seleccionar más de una.": "nuevas_tecnologias",
    "Entendiendo el aprendizaje automático como un tipo de IA que proporciona a las computadoras la capacidad de aprender, sin ser programadas explícitamente. ¿Usa o usaría está herramienta en su biblioteca para realizar labores propias de esta tales como: desarrollar las colecciones, recuperar información, agregar metadatos?": "uso_de_IA",
    "Ha adoptado o adoptaría alguna de las siguientes tecnologías en su biblioteca. Puede seleccionar más de una": "adopcion_de_tecnologia",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Internet de las cosas]": "impacto_en_bibliotecas_iot",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Acceso Abierto]": "impacto_en_bibliotecas_open",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Software Libre]": "impacto_en_bibliotecas_libre",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Política Nacional sobre avances tecnológicos (como la IA)]": "impacto_en_bibliotecas_politica",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Asesores virtuales para estudiantes]": "impacto_en_bibliotecas_asesores",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Protección de datos personales]": "impacto_en_bibliotecas_datos_personales",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Privacidad de la información]": "impacto_en_bibliotecas_privacidad",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Derechos de autor]": "impacto_en_bibliotecas:derechosautor",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Recursos educacionales de acceso abierto a través de internet]": "impacto_en_bibliotecas_internet",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Inteligencia artificial]": "impacto_en_bibliotecas_ia",
    "Tomando en consideración los próximos 10 años, ¿qué impacto tendría la IA en alguno de los siguientes aspectos de su biblioteca? ( Considere que 1 es poco impacto y 5 alto impacto) [Humanidades digitales]": "impacto_en_bibliotecas_humanidades",
    "¿Considera que su biblioteca está preparada para los cambios que podría traer el avance de la tecnología de IA?": "cambios_en_biblioteca",
    "Considerando lo anterior ¿ante los constantes y acelerados avances en la tecnología y los modelos de IA, piensa que es posible capacitar al equipo de la biblioteca en sus usos?": "posible_capacitacion",
    "¿Considera usted que sistemas automatizados o máquinas inteligentes pueden reemplazar a los equipos de biblioteca?": "posibilidad_reemplazo",
}
